type SikakuListType = {
  [key: string]: string[];
};

export const SIKAKU_LIST: SikakuListType = {
  情報処理技術者試験: [
    "選択してください",
    "ITストラテジスト試験",
    "システム監査技術者試験",
    "プロジェクトマネージャ試験",
    "システムアーキテクト試験",
    "ITサービスマネージャ試験",
    "ネットワークスペシャリスト試験",
    "データベーススペシャリスト試験",
    "エンベデッドシステムスペシャリスト試験",
    "情報処理安全確保支援士試験",
    "応用情報技術者試験",
    "基本情報技術者試験",
    "情報セキュリティマネジメント試験",
  ],
  ORACLE: [
    "選択してください",
    "ORACLE MASTER Platinum Oracle Database",
    "ORACLE MASTER Gold Oracle Database",
    "ORACLE MASTER Silver Oracle Database",
    "ORACLE MASTER Bronze Oracle Database",
    "ORACLE MASTER Gold Oracle PL/SQL Developer",
    "ORACLE MASTER Silver Oracle PL/SQL Developer",
    "Oracle Certified Professional MySQL",
    "Oracle Certified Associate MySQL",
    "Programmer Gold",
    "Programmer Professional",
    "Oracle Certified Java Programmer, Silver",
    "Oracle Certified Java Programmer, Associate",
    "Oracle Certified Java Programmer, Bronze SE8",
  ],
  Microsoft: [
    "選択してください",
    "Microsoft Certified Solutions Expert / Microsoft Certified Expert",
    "Microsoft Certified Solutions Developer",
    "Microsoft Certified Solutions Associate / Microsoft Certified Associate",
    "Microsoft Certified Fundamentals",
  ],
  CISCO: [
    "選択してください",
    "CCDA",
    "CCDP",
    "CCDP-WAN Switching",
    "CCIE-RS",
    "CCIE-WAN Switching",
    "CCIR-ISP DIAL",
    "CCNA",
    "CCNA-WAN Switching",
    "CCNP",
    "CCNP-WAN Switching",
  ],
  AWS: [
    "選択してください",
    "AWS Certified Solutions Architect - Professional",
    "AWS Certified DevOps Engineer - Professional",
    "AWS Certified Solutions Architect - Associate",
    "AWS Certified SysOps Administrator-Associate",
    "AWS Certified Developer - Associate",
  ],
  Python: [
    "選択してください",
    "Python 3 エンジニア認定データ分析試験",
    "Python 3 エンジニア認定基礎試験",
  ],
  日本ディープランニング協会: ["選択してください", "G検定", "E資格"],
  OutSystems: [
    "選択してください",
    "Expert Traditional Web Developer  (OutSystems 11)",
    "Professional Traditional Web Developer  (OutSystems 11)",
  ],
  富士通: [
    "選択してください",
    "FUJITSU Certified Senior Master",
    "FUJITSU Certified Master",
    "FUJITSU Certified Senior Professional",
    "FUJITSU Certified Professional",
  ],
  一般社団法人PMI日本支部: [
    "選択してください",
    "PMP(Project Management Profes)",
  ],
  CompTIA: [
    "選択してください",
    "Advanced Security Practitioner",
    "Cloud Essentials",
    "Mobility+",
    "Cloud+",
    "Project+",
    "CDIA+",
    "CTT+",
    "Storage+",
    "Powered by SNIA Server+",
    "Security+",
    "Network+ A+",
  ],
  Linux: [
    "選択してください",
    "LPICレベル3・LinuCレベル3",
    "LPICレベル2・LinuCレベル2",
  ],
  HTML5プロフェッショナル: [
    "選択してください",
    "HTML5 Professional Certification Level.2",
    "HTML5 Professional Certification Level.1",
  ],
  XMLマスター: [
    "選択してください",
    "XMLマスター:プロフェッショナル",
    "XMLマスター:ベーシック",
  ],
};
